### ISSUE TITLE
Line6 HX Stomp : no sound after jack session

### ISSUE THREAD

**Issue by newlaurent62** [poljar/pulseaudio#1]
After a Jack session (jackd2), i have no sound with pulseaudio when i try to use the Line6 HX Stomp even if the volume gauge indicates that there is sound on the application and on the sound card output ... If i come back to jack, it works with Jack.

I don't know where to find help.

It works as expected with my other soundcards.

I use pulseaudio 13.99.1

**Comment by poljar** [comment]
Help for PulseAudio can be found on their official gitlab [here](https://gitlab.freedesktop.org/groups/pulseaudio/-/issues) or on the official mailing list over [here](https://lists.freedesktop.org/mailman/listinfo/pulseaudio-discuss).

I'm afraid that I don't have any experience with Jack/Pulse but this sounds like Jack is taking control over the card and not yielding it back to Pulse. Perhaps some configuration or enabling `module-jackdbus-detect` is needed on the Pulse side.

But help is best found on the official project channels.

Best of luck.

**Comment by newlaurent62** [comment]
Thanks for the links ! :-)

**Comment by newlaurent62** [comment]
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/874
